1st task
js-tasks-ru/jsbasic-20230209_evgeniy081 pull request #4
Opened 2023-03-13 21:32 UTC by CookieWithJam

2023-03-13 21:34 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-03-13 21:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-13 21:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2023-03-14 05:08 UTC, koalex requested changes
Исправить замечание в **2-2**

2023-03-14 05:08 UTC, koalex commented on 2-module/2-task/index.js
> +  return arr == 0;
Несмотря на то, что тесты ОК (ошибка в тестах) - это неправильное решение.
`arr` - это массив и вы сравниваете массив с числом `0`. Массив и число - это разные типы данных и они никогда не будут равны друг другу. Если править ваше решение, то должно быть как минимум вот так:
`return arr.length === 0;`

2023-03-14 20:33 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-03-14 20:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2023-03-14 20:41 UTC, CookieWithJam commented on 2-module/2-task/index.js
> +  return arr == 0;
В задачнике можно нажать на "Посмотреть решение преподавателя", но после решения она пропадает. Можно ли где-то посмотреть более лакончиные решения задач?

2023-03-15 20:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2023-03-15 21:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2023-03-16 03:11 UTC, koalex commented on 2-module/2-task/index.js
> +  return arr == 0;
Да, всё верно верно после решения нельзя увидеть решение преподавателя. Можете написать мне и я скину его вам. Для **2-2** решение вот:
```
function isEmpty(obj) {
  for (const key in obj) {
    return false;
  }
  return true;
}
```

2023-03-16 03:11 UTC, koalex approved these changes

2023-03-16 03:12 UTC, merged